config/routes.rb
Rails.application.routes.draw do

  root to: 'posts#index'

  resources :posts do
    resources :tags
  end
  
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_and_belongs_to_many :tags
  validates :title, :presence => true
  validates :content, :presence => true
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :posts
  validates :name, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    post = Post.find(params[:id])
    post.tag.each do |tag|
    tag.destroy
    end
    post.destroy
    redirect_to post_path
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to posts_path(@post)
    else
      render :edit
    end
  end

  private
  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
  end

  def new
    @post = Post.find(params[:post_id])
    @tag = @post.tags.new
  end

  def create
    @post = Post.find(params[:post_id])
    @tag = @post.tags.new(tag_params)
    if @tag.save
      redirect_to post_path(@tag.post)
    else
      render :new
    end
  end

  def show
    @tag = Tag.find(params[:id])
    @post = @tag.post
  end

  def destroy
    @tag = Tag.find(params[:id])
    tag.destroy
    redirect_to post_path(@post)
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def update
    @tag = Tag.find(params[:id])
    if @tag.update(tag_params)
      redirect_to tag_path(@tag)
    else
      render :edit
    end
  end

  private
    def artist_params
      params.require(:artist).permit(:name)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>There was an error. Please try again:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogCr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= render "layouts/errors", :object => @post %>

<%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render "form" %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<%= link_to "New Post", new_post_path, class: "btn btn-primary" %>

<h3>Here are all the Posts!</h3>

<ul>
  <% @posts.each do |post| %>
    <li><%= link_to "#{post.title}", posts_path(post) %></li>
  <% end %>
</ul>

app/views/posts/new.html.erb
<h1>New Posts</h1>

<%= render "form" %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<p> <%= link_to "Add a tag", new_post_tag_path(@post) %></p>


<p> <%= link_to "Delete post", posts_path(@post), :data => {confirm: "Are you sure?", method: "delete"}, class: "btn btn-danger" %></p>

<p><%= link_to "Return to Posts", posts_path%></p>

<% if @post.tags.any? %>
  <h4> Here are the tasks for this list:</h4>

<ul>
  <% @post.tags.each do |tag| %>
    <li>
      <%= tag.name %>
      <%= link_to "Edit", edit_post_tag_path(@post, tag) %>
      <%= link_to "Delete", post_tag_path(@post, tag), :data => {confirm: "Are Your Sure?", method: "delete"}, class: "btn btn-danger"%>
    </li>
  <% end %>
</ul>
  <% else %>
    <p>There are no tags yet!</p>
<% end %>

app/views/tags/_form.html.erb
<%= render('layouts/errors', :object => @tag) %>

<%= form_for [@post, @task] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
<p><%= f.submit class: "btn btn-primary"%></p>
<% end %>

app/views/tags/new.html.erb
<h1>New task for <%= @post.title %></h1>

<%= render 'form'%>